// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.spinn3r.api.protobuf;

public final class ContentExtension {
  private ContentExtension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Wrapper extends
      com.google.protobuf.GeneratedMessage {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper() {}
    
    private static final Wrapper defaultInstance = new Wrapper();
    public static Wrapper getDefaultInstance() {
      return defaultInstance;
    }
    
    public Wrapper getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Wrapper_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Wrapper_fieldAccessorTable;
    }
    
    // optional .contentExtension.Twitter twitter = 1;
    public static final int TWITTER_FIELD_NUMBER = 1;
    private boolean hasTwitter;
    private com.spinn3r.api.protobuf.ContentExtension.Twitter twitter_ = com.spinn3r.api.protobuf.ContentExtension.Twitter.getDefaultInstance();
    public boolean hasTwitter() { return hasTwitter; }
    public com.spinn3r.api.protobuf.ContentExtension.Twitter getTwitter() { return twitter_; }
    
    // optional .contentExtension.LinkRankNode linkRankNode = 2;
    public static final int LINKRANKNODE_FIELD_NUMBER = 2;
    private boolean hasLinkRankNode;
    private com.spinn3r.api.protobuf.ContentExtension.LinkRankNode linkRankNode_ = com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDefaultInstance();
    public boolean hasLinkRankNode() { return hasLinkRankNode; }
    public com.spinn3r.api.protobuf.ContentExtension.LinkRankNode getLinkRankNode() { return linkRankNode_; }
    
    // optional .contentExtension.Timestamp timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private com.spinn3r.api.protobuf.ContentExtension.Timestamp timestamp_ = com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDefaultInstance();
    public boolean hasTimestamp() { return hasTimestamp; }
    public com.spinn3r.api.protobuf.ContentExtension.Timestamp getTimestamp() { return timestamp_; }
    
    public final boolean isInitialized() {
      if (hasLinkRankNode()) {
        if (!getLinkRankNode().isInitialized()) return false;
      }
      if (hasTimestamp()) {
        if (!getTimestamp().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasTwitter()) {
        output.writeMessage(1, getTwitter());
      }
      if (hasLinkRankNode()) {
        output.writeMessage(2, getLinkRankNode());
      }
      if (hasTimestamp()) {
        output.writeMessage(3, getTimestamp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTwitter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTwitter());
      }
      if (hasLinkRankNode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLinkRankNode());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ContentExtension.Wrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ContentExtension.Wrapper result;
      
      // Construct using com.spinn3r.api.protobuf.ContentExtension.Wrapper.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ContentExtension.Wrapper();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ContentExtension.Wrapper internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ContentExtension.Wrapper();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Wrapper.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Wrapper getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Wrapper.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ContentExtension.Wrapper build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ContentExtension.Wrapper buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Wrapper buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ContentExtension.Wrapper returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ContentExtension.Wrapper) {
          return mergeFrom((com.spinn3r.api.protobuf.ContentExtension.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ContentExtension.Wrapper other) {
        if (other == com.spinn3r.api.protobuf.ContentExtension.Wrapper.getDefaultInstance()) return this;
        if (other.hasTwitter()) {
          mergeTwitter(other.getTwitter());
        }
        if (other.hasLinkRankNode()) {
          mergeLinkRankNode(other.getLinkRankNode());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.spinn3r.api.protobuf.ContentExtension.Twitter.Builder subBuilder = com.spinn3r.api.protobuf.ContentExtension.Twitter.newBuilder();
              if (hasTwitter()) {
                subBuilder.mergeFrom(getTwitter());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTwitter(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.Builder subBuilder = com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.newBuilder();
              if (hasLinkRankNode()) {
                subBuilder.mergeFrom(getLinkRankNode());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLinkRankNode(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.spinn3r.api.protobuf.ContentExtension.Timestamp.Builder subBuilder = com.spinn3r.api.protobuf.ContentExtension.Timestamp.newBuilder();
              if (hasTimestamp()) {
                subBuilder.mergeFrom(getTimestamp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTimestamp(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .contentExtension.Twitter twitter = 1;
      public boolean hasTwitter() {
        return result.hasTwitter();
      }
      public com.spinn3r.api.protobuf.ContentExtension.Twitter getTwitter() {
        return result.getTwitter();
      }
      public Builder setTwitter(com.spinn3r.api.protobuf.ContentExtension.Twitter value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTwitter = true;
        result.twitter_ = value;
        return this;
      }
      public Builder setTwitter(com.spinn3r.api.protobuf.ContentExtension.Twitter.Builder builderForValue) {
        result.hasTwitter = true;
        result.twitter_ = builderForValue.build();
        return this;
      }
      public Builder mergeTwitter(com.spinn3r.api.protobuf.ContentExtension.Twitter value) {
        if (result.hasTwitter() &&
            result.twitter_ != com.spinn3r.api.protobuf.ContentExtension.Twitter.getDefaultInstance()) {
          result.twitter_ =
            com.spinn3r.api.protobuf.ContentExtension.Twitter.newBuilder(result.twitter_).mergeFrom(value).buildPartial();
        } else {
          result.twitter_ = value;
        }
        result.hasTwitter = true;
        return this;
      }
      public Builder clearTwitter() {
        result.hasTwitter = false;
        result.twitter_ = com.spinn3r.api.protobuf.ContentExtension.Twitter.getDefaultInstance();
        return this;
      }
      
      // optional .contentExtension.LinkRankNode linkRankNode = 2;
      public boolean hasLinkRankNode() {
        return result.hasLinkRankNode();
      }
      public com.spinn3r.api.protobuf.ContentExtension.LinkRankNode getLinkRankNode() {
        return result.getLinkRankNode();
      }
      public Builder setLinkRankNode(com.spinn3r.api.protobuf.ContentExtension.LinkRankNode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLinkRankNode = true;
        result.linkRankNode_ = value;
        return this;
      }
      public Builder setLinkRankNode(com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.Builder builderForValue) {
        result.hasLinkRankNode = true;
        result.linkRankNode_ = builderForValue.build();
        return this;
      }
      public Builder mergeLinkRankNode(com.spinn3r.api.protobuf.ContentExtension.LinkRankNode value) {
        if (result.hasLinkRankNode() &&
            result.linkRankNode_ != com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDefaultInstance()) {
          result.linkRankNode_ =
            com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.newBuilder(result.linkRankNode_).mergeFrom(value).buildPartial();
        } else {
          result.linkRankNode_ = value;
        }
        result.hasLinkRankNode = true;
        return this;
      }
      public Builder clearLinkRankNode() {
        result.hasLinkRankNode = false;
        result.linkRankNode_ = com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDefaultInstance();
        return this;
      }
      
      // optional .contentExtension.Timestamp timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public com.spinn3r.api.protobuf.ContentExtension.Timestamp getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(com.spinn3r.api.protobuf.ContentExtension.Timestamp value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder setTimestamp(com.spinn3r.api.protobuf.ContentExtension.Timestamp.Builder builderForValue) {
        result.hasTimestamp = true;
        result.timestamp_ = builderForValue.build();
        return this;
      }
      public Builder mergeTimestamp(com.spinn3r.api.protobuf.ContentExtension.Timestamp value) {
        if (result.hasTimestamp() &&
            result.timestamp_ != com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDefaultInstance()) {
          result.timestamp_ =
            com.spinn3r.api.protobuf.ContentExtension.Timestamp.newBuilder(result.timestamp_).mergeFrom(value).buildPartial();
        } else {
          result.timestamp_ = value;
        }
        result.hasTimestamp = true;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDefaultInstance();
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.getDescriptor();
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.internalForceInit();
    }
  }
  
  public static final class Twitter extends
      com.google.protobuf.GeneratedMessage {
    // Use Twitter.newBuilder() to construct.
    private Twitter() {}
    
    private static final Twitter defaultInstance = new Twitter();
    public static Twitter getDefaultInstance() {
      return defaultInstance;
    }
    
    public Twitter getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Twitter_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Twitter_fieldAccessorTable;
    }
    
    // optional uint32 followers = 1;
    public static final int FOLLOWERS_FIELD_NUMBER = 1;
    private boolean hasFollowers;
    private int followers_ = 0;
    public boolean hasFollowers() { return hasFollowers; }
    public int getFollowers() { return followers_; }
    
    // optional uint32 friends = 2;
    public static final int FRIENDS_FIELD_NUMBER = 2;
    private boolean hasFriends;
    private int friends_ = 0;
    public boolean hasFriends() { return hasFriends; }
    public int getFriends() { return friends_; }
    
    // optional string location = 3;
    public static final int LOCATION_FIELD_NUMBER = 3;
    private boolean hasLocation;
    private java.lang.String location_ = "";
    public boolean hasLocation() { return hasLocation; }
    public java.lang.String getLocation() { return location_; }
    
    // optional string profile_image_url = 4;
    public static final int PROFILE_IMAGE_URL_FIELD_NUMBER = 4;
    private boolean hasProfileImageUrl;
    private java.lang.String profileImageUrl_ = "";
    public boolean hasProfileImageUrl() { return hasProfileImageUrl; }
    public java.lang.String getProfileImageUrl() { return profileImageUrl_; }
    
    // optional string lang = 5;
    public static final int LANG_FIELD_NUMBER = 5;
    private boolean hasLang;
    private java.lang.String lang_ = "";
    public boolean hasLang() { return hasLang; }
    public java.lang.String getLang() { return lang_; }
    
    // optional uint32 statuses_count = 6;
    public static final int STATUSES_COUNT_FIELD_NUMBER = 6;
    private boolean hasStatusesCount;
    private int statusesCount_ = 0;
    public boolean hasStatusesCount() { return hasStatusesCount; }
    public int getStatusesCount() { return statusesCount_; }
    
    // optional bool verified = 7;
    public static final int VERIFIED_FIELD_NUMBER = 7;
    private boolean hasVerified;
    private boolean verified_ = false;
    public boolean hasVerified() { return hasVerified; }
    public boolean getVerified() { return verified_; }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasFollowers()) {
        output.writeUInt32(1, getFollowers());
      }
      if (hasFriends()) {
        output.writeUInt32(2, getFriends());
      }
      if (hasLocation()) {
        output.writeString(3, getLocation());
      }
      if (hasProfileImageUrl()) {
        output.writeString(4, getProfileImageUrl());
      }
      if (hasLang()) {
        output.writeString(5, getLang());
      }
      if (hasStatusesCount()) {
        output.writeUInt32(6, getStatusesCount());
      }
      if (hasVerified()) {
        output.writeBool(7, getVerified());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFollowers()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getFollowers());
      }
      if (hasFriends()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getFriends());
      }
      if (hasLocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getLocation());
      }
      if (hasProfileImageUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getProfileImageUrl());
      }
      if (hasLang()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLang());
      }
      if (hasStatusesCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getStatusesCount());
      }
      if (hasVerified()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getVerified());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Twitter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ContentExtension.Twitter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ContentExtension.Twitter result;
      
      // Construct using com.spinn3r.api.protobuf.ContentExtension.Twitter.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ContentExtension.Twitter();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ContentExtension.Twitter internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ContentExtension.Twitter();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Twitter.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Twitter getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Twitter.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ContentExtension.Twitter build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ContentExtension.Twitter buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Twitter buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ContentExtension.Twitter returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ContentExtension.Twitter) {
          return mergeFrom((com.spinn3r.api.protobuf.ContentExtension.Twitter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ContentExtension.Twitter other) {
        if (other == com.spinn3r.api.protobuf.ContentExtension.Twitter.getDefaultInstance()) return this;
        if (other.hasFollowers()) {
          setFollowers(other.getFollowers());
        }
        if (other.hasFriends()) {
          setFriends(other.getFriends());
        }
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        if (other.hasProfileImageUrl()) {
          setProfileImageUrl(other.getProfileImageUrl());
        }
        if (other.hasLang()) {
          setLang(other.getLang());
        }
        if (other.hasStatusesCount()) {
          setStatusesCount(other.getStatusesCount());
        }
        if (other.hasVerified()) {
          setVerified(other.getVerified());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setFollowers(input.readUInt32());
              break;
            }
            case 16: {
              setFriends(input.readUInt32());
              break;
            }
            case 26: {
              setLocation(input.readString());
              break;
            }
            case 34: {
              setProfileImageUrl(input.readString());
              break;
            }
            case 42: {
              setLang(input.readString());
              break;
            }
            case 48: {
              setStatusesCount(input.readUInt32());
              break;
            }
            case 56: {
              setVerified(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 followers = 1;
      public boolean hasFollowers() {
        return result.hasFollowers();
      }
      public int getFollowers() {
        return result.getFollowers();
      }
      public Builder setFollowers(int value) {
        result.hasFollowers = true;
        result.followers_ = value;
        return this;
      }
      public Builder clearFollowers() {
        result.hasFollowers = false;
        result.followers_ = 0;
        return this;
      }
      
      // optional uint32 friends = 2;
      public boolean hasFriends() {
        return result.hasFriends();
      }
      public int getFriends() {
        return result.getFriends();
      }
      public Builder setFriends(int value) {
        result.hasFriends = true;
        result.friends_ = value;
        return this;
      }
      public Builder clearFriends() {
        result.hasFriends = false;
        result.friends_ = 0;
        return this;
      }
      
      // optional string location = 3;
      public boolean hasLocation() {
        return result.hasLocation();
      }
      public java.lang.String getLocation() {
        return result.getLocation();
      }
      public Builder setLocation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLocation = true;
        result.location_ = value;
        return this;
      }
      public Builder clearLocation() {
        result.hasLocation = false;
        result.location_ = getDefaultInstance().getLocation();
        return this;
      }
      
      // optional string profile_image_url = 4;
      public boolean hasProfileImageUrl() {
        return result.hasProfileImageUrl();
      }
      public java.lang.String getProfileImageUrl() {
        return result.getProfileImageUrl();
      }
      public Builder setProfileImageUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProfileImageUrl = true;
        result.profileImageUrl_ = value;
        return this;
      }
      public Builder clearProfileImageUrl() {
        result.hasProfileImageUrl = false;
        result.profileImageUrl_ = getDefaultInstance().getProfileImageUrl();
        return this;
      }
      
      // optional string lang = 5;
      public boolean hasLang() {
        return result.hasLang();
      }
      public java.lang.String getLang() {
        return result.getLang();
      }
      public Builder setLang(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLang = true;
        result.lang_ = value;
        return this;
      }
      public Builder clearLang() {
        result.hasLang = false;
        result.lang_ = getDefaultInstance().getLang();
        return this;
      }
      
      // optional uint32 statuses_count = 6;
      public boolean hasStatusesCount() {
        return result.hasStatusesCount();
      }
      public int getStatusesCount() {
        return result.getStatusesCount();
      }
      public Builder setStatusesCount(int value) {
        result.hasStatusesCount = true;
        result.statusesCount_ = value;
        return this;
      }
      public Builder clearStatusesCount() {
        result.hasStatusesCount = false;
        result.statusesCount_ = 0;
        return this;
      }
      
      // optional bool verified = 7;
      public boolean hasVerified() {
        return result.hasVerified();
      }
      public boolean getVerified() {
        return result.getVerified();
      }
      public Builder setVerified(boolean value) {
        result.hasVerified = true;
        result.verified_ = value;
        return this;
      }
      public Builder clearVerified() {
        result.hasVerified = false;
        result.verified_ = false;
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.getDescriptor();
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.internalForceInit();
    }
  }
  
  public static final class LinkRankNode extends
      com.google.protobuf.GeneratedMessage {
    // Use LinkRankNode.newBuilder() to construct.
    private LinkRankNode() {}
    
    private static final LinkRankNode defaultInstance = new LinkRankNode();
    public static LinkRankNode getDefaultInstance() {
      return defaultInstance;
    }
    
    public LinkRankNode getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_LinkRankNode_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_LinkRankNode_fieldAccessorTable;
    }
    
    // required double rank = 1;
    public static final int RANK_FIELD_NUMBER = 1;
    private boolean hasRank;
    private double rank_ = 0D;
    public boolean hasRank() { return hasRank; }
    public double getRank() { return rank_; }
    
    // required uint32 indegree = 2;
    public static final int INDEGREE_FIELD_NUMBER = 2;
    private boolean hasIndegree;
    private int indegree_ = 0;
    public boolean hasIndegree() { return hasIndegree; }
    public int getIndegree() { return indegree_; }
    
    // required uint32 outdegree = 3;
    public static final int OUTDEGREE_FIELD_NUMBER = 3;
    private boolean hasOutdegree;
    private int outdegree_ = 0;
    public boolean hasOutdegree() { return hasOutdegree; }
    public int getOutdegree() { return outdegree_; }
    
    // required string resource = 4;
    public static final int RESOURCE_FIELD_NUMBER = 4;
    private boolean hasResource;
    private java.lang.String resource_ = "";
    public boolean hasResource() { return hasResource; }
    public java.lang.String getResource() { return resource_; }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    public final boolean isInitialized() {
      if (!hasRank) return false;
      if (!hasIndegree) return false;
      if (!hasOutdegree) return false;
      if (!hasResource) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasRank()) {
        output.writeDouble(1, getRank());
      }
      if (hasIndegree()) {
        output.writeUInt32(2, getIndegree());
      }
      if (hasOutdegree()) {
        output.writeUInt32(3, getOutdegree());
      }
      if (hasResource()) {
        output.writeString(4, getResource());
      }
      if (hasName()) {
        output.writeString(5, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRank()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, getRank());
      }
      if (hasIndegree()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getIndegree());
      }
      if (hasOutdegree()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getOutdegree());
      }
      if (hasResource()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getResource());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.LinkRankNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ContentExtension.LinkRankNode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ContentExtension.LinkRankNode result;
      
      // Construct using com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ContentExtension.LinkRankNode();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ContentExtension.LinkRankNode internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ContentExtension.LinkRankNode();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.LinkRankNode getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ContentExtension.LinkRankNode build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ContentExtension.LinkRankNode buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.LinkRankNode buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ContentExtension.LinkRankNode returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ContentExtension.LinkRankNode) {
          return mergeFrom((com.spinn3r.api.protobuf.ContentExtension.LinkRankNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ContentExtension.LinkRankNode other) {
        if (other == com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.getDefaultInstance()) return this;
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasIndegree()) {
          setIndegree(other.getIndegree());
        }
        if (other.hasOutdegree()) {
          setOutdegree(other.getOutdegree());
        }
        if (other.hasResource()) {
          setResource(other.getResource());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 9: {
              setRank(input.readDouble());
              break;
            }
            case 16: {
              setIndegree(input.readUInt32());
              break;
            }
            case 24: {
              setOutdegree(input.readUInt32());
              break;
            }
            case 34: {
              setResource(input.readString());
              break;
            }
            case 42: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required double rank = 1;
      public boolean hasRank() {
        return result.hasRank();
      }
      public double getRank() {
        return result.getRank();
      }
      public Builder setRank(double value) {
        result.hasRank = true;
        result.rank_ = value;
        return this;
      }
      public Builder clearRank() {
        result.hasRank = false;
        result.rank_ = 0D;
        return this;
      }
      
      // required uint32 indegree = 2;
      public boolean hasIndegree() {
        return result.hasIndegree();
      }
      public int getIndegree() {
        return result.getIndegree();
      }
      public Builder setIndegree(int value) {
        result.hasIndegree = true;
        result.indegree_ = value;
        return this;
      }
      public Builder clearIndegree() {
        result.hasIndegree = false;
        result.indegree_ = 0;
        return this;
      }
      
      // required uint32 outdegree = 3;
      public boolean hasOutdegree() {
        return result.hasOutdegree();
      }
      public int getOutdegree() {
        return result.getOutdegree();
      }
      public Builder setOutdegree(int value) {
        result.hasOutdegree = true;
        result.outdegree_ = value;
        return this;
      }
      public Builder clearOutdegree() {
        result.hasOutdegree = false;
        result.outdegree_ = 0;
        return this;
      }
      
      // required string resource = 4;
      public boolean hasResource() {
        return result.hasResource();
      }
      public java.lang.String getResource() {
        return result.getResource();
      }
      public Builder setResource(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasResource = true;
        result.resource_ = value;
        return this;
      }
      public Builder clearResource() {
        result.hasResource = false;
        result.resource_ = getDefaultInstance().getResource();
        return this;
      }
      
      // optional string name = 5;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.getDescriptor();
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.internalForceInit();
    }
  }
  
  public static final class Timestamp extends
      com.google.protobuf.GeneratedMessage {
    // Use Timestamp.newBuilder() to construct.
    private Timestamp() {}
    
    private static final Timestamp defaultInstance = new Timestamp();
    public static Timestamp getDefaultInstance() {
      return defaultInstance;
    }
    
    public Timestamp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Timestamp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ContentExtension.internal_static_contentExtension_Timestamp_fieldAccessorTable;
    }
    
    // required string original = 1;
    public static final int ORIGINAL_FIELD_NUMBER = 1;
    private boolean hasOriginal;
    private java.lang.String original_ = "";
    public boolean hasOriginal() { return hasOriginal; }
    public java.lang.String getOriginal() { return original_; }
    
    public final boolean isInitialized() {
      if (!hasOriginal) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasOriginal()) {
        output.writeString(1, getOriginal());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOriginal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getOriginal());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ContentExtension.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ContentExtension.Timestamp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ContentExtension.Timestamp result;
      
      // Construct using com.spinn3r.api.protobuf.ContentExtension.Timestamp.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ContentExtension.Timestamp();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ContentExtension.Timestamp internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ContentExtension.Timestamp();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Timestamp getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ContentExtension.Timestamp build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ContentExtension.Timestamp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ContentExtension.Timestamp buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ContentExtension.Timestamp returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ContentExtension.Timestamp) {
          return mergeFrom((com.spinn3r.api.protobuf.ContentExtension.Timestamp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ContentExtension.Timestamp other) {
        if (other == com.spinn3r.api.protobuf.ContentExtension.Timestamp.getDefaultInstance()) return this;
        if (other.hasOriginal()) {
          setOriginal(other.getOriginal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setOriginal(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string original = 1;
      public boolean hasOriginal() {
        return result.hasOriginal();
      }
      public java.lang.String getOriginal() {
        return result.getOriginal();
      }
      public Builder setOriginal(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOriginal = true;
        result.original_ = value;
        return this;
      }
      public Builder clearOriginal() {
        result.hasOriginal = false;
        result.original_ = getDefaultInstance().getOriginal();
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.getDescriptor();
    }
    
    static {
      com.spinn3r.api.protobuf.ContentExtension.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contentExtension_Wrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contentExtension_Wrapper_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contentExtension_Twitter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contentExtension_Twitter_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contentExtension_LinkRankNode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contentExtension_LinkRankNode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_contentExtension_Timestamp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_contentExtension_Timestamp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026contentExtension.proto\022\020contentExtensi" +
      "on\"\233\001\n\007Wrapper\022*\n\007twitter\030\001 \001(\0132\031.conten" +
      "tExtension.Twitter\0224\n\014linkRankNode\030\002 \001(\013" +
      "2\036.contentExtension.LinkRankNode\022.\n\ttime" +
      "stamp\030\003 \001(\0132\033.contentExtension.Timestamp" +
      "\"\222\001\n\007Twitter\022\021\n\tfollowers\030\001 \001(\r\022\017\n\007frien" +
      "ds\030\002 \001(\r\022\020\n\010location\030\003 \001(\t\022\031\n\021profile_im" +
      "age_url\030\004 \001(\t\022\014\n\004lang\030\005 \001(\t\022\026\n\016statuses_" +
      "count\030\006 \001(\r\022\020\n\010verified\030\007 \001(\010\"a\n\014LinkRan" +
      "kNode\022\014\n\004rank\030\001 \002(\001\022\020\n\010indegree\030\002 \002(\r\022\021\n",
      "\toutdegree\030\003 \002(\r\022\020\n\010resource\030\004 \002(\t\022\014\n\004na" +
      "me\030\005 \001(\t\"\035\n\tTimestamp\022\020\n\010original\030\001 \002(\tB" +
      ",\n\030com.spinn3r.api.protobufB\020ContentExte" +
      "nsion"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_contentExtension_Wrapper_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_contentExtension_Wrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contentExtension_Wrapper_descriptor,
              new java.lang.String[] { "Twitter", "LinkRankNode", "Timestamp", },
              com.spinn3r.api.protobuf.ContentExtension.Wrapper.class,
              com.spinn3r.api.protobuf.ContentExtension.Wrapper.Builder.class);
          internal_static_contentExtension_Twitter_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_contentExtension_Twitter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contentExtension_Twitter_descriptor,
              new java.lang.String[] { "Followers", "Friends", "Location", "ProfileImageUrl", "Lang", "StatusesCount", "Verified", },
              com.spinn3r.api.protobuf.ContentExtension.Twitter.class,
              com.spinn3r.api.protobuf.ContentExtension.Twitter.Builder.class);
          internal_static_contentExtension_LinkRankNode_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_contentExtension_LinkRankNode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contentExtension_LinkRankNode_descriptor,
              new java.lang.String[] { "Rank", "Indegree", "Outdegree", "Resource", "Name", },
              com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.class,
              com.spinn3r.api.protobuf.ContentExtension.LinkRankNode.Builder.class);
          internal_static_contentExtension_Timestamp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_contentExtension_Timestamp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_contentExtension_Timestamp_descriptor,
              new java.lang.String[] { "Original", },
              com.spinn3r.api.protobuf.ContentExtension.Timestamp.class,
              com.spinn3r.api.protobuf.ContentExtension.Timestamp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
