// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoStream.proto

package com.spinn3r.api.protobuf;

public final class ProtoStream {
  private ProtoStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ApplacationHeader extends
      com.google.protobuf.GeneratedMessage {
    // Use ApplacationHeader.newBuilder() to construct.
    private ApplacationHeader() {
      initFields();
    }
    private ApplacationHeader(boolean noInit) {}
    
    private static final ApplacationHeader defaultInstance;
    public static ApplacationHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public ApplacationHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ApplacationHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ApplacationHeader_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader result;
      
      // Construct using com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader) {
          return mergeFrom((com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader other) {
        if (other == com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protoStream.ApplacationHeader)
    }
    
    static {
      defaultInstance = new ApplacationHeader(true);
      com.spinn3r.api.protobuf.ProtoStream.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protoStream.ApplacationHeader)
  }
  
  public static final class ProtoStreamHeader extends
      com.google.protobuf.GeneratedMessage {
    // Use ProtoStreamHeader.newBuilder() to construct.
    private ProtoStreamHeader() {
      initFields();
    }
    private ProtoStreamHeader(boolean noInit) {}
    
    private static final ProtoStreamHeader defaultInstance;
    public static ProtoStreamHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoStreamHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ProtoStreamHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ProtoStreamHeader_fieldAccessorTable;
    }
    
    // required string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private boolean hasVersion;
    private java.lang.String version_ = "";
    public boolean hasVersion() { return hasVersion; }
    public java.lang.String getVersion() { return version_; }
    
    // required string default_entry_type = 2;
    public static final int DEFAULT_ENTRY_TYPE_FIELD_NUMBER = 2;
    private boolean hasDefaultEntryType;
    private java.lang.String defaultEntryType_ = "";
    public boolean hasDefaultEntryType() { return hasDefaultEntryType; }
    public java.lang.String getDefaultEntryType() { return defaultEntryType_; }
    
    // repeated .protoStream.ApplacationHeader applacation_header = 3;
    public static final int APPLACATION_HEADER_FIELD_NUMBER = 3;
    private java.util.List<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader> applacationHeader_ =
      java.util.Collections.emptyList();
    public java.util.List<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader> getApplacationHeaderList() {
      return applacationHeader_;
    }
    public int getApplacationHeaderCount() { return applacationHeader_.size(); }
    public com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader getApplacationHeader(int index) {
      return applacationHeader_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasVersion) return false;
      if (!hasDefaultEntryType) return false;
      for (com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader element : getApplacationHeaderList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVersion()) {
        output.writeString(1, getVersion());
      }
      if (hasDefaultEntryType()) {
        output.writeString(2, getDefaultEntryType());
      }
      for (com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader element : getApplacationHeaderList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVersion());
      }
      if (hasDefaultEntryType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDefaultEntryType());
      }
      for (com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader element : getApplacationHeaderList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader result;
      
      // Construct using com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.applacationHeader_ != java.util.Collections.EMPTY_LIST) {
          result.applacationHeader_ =
            java.util.Collections.unmodifiableList(result.applacationHeader_);
        }
        com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader) {
          return mergeFrom((com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader other) {
        if (other == com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasDefaultEntryType()) {
          setDefaultEntryType(other.getDefaultEntryType());
        }
        if (!other.applacationHeader_.isEmpty()) {
          if (result.applacationHeader_.isEmpty()) {
            result.applacationHeader_ = new java.util.ArrayList<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader>();
          }
          result.applacationHeader_.addAll(other.applacationHeader_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setVersion(input.readString());
              break;
            }
            case 18: {
              setDefaultEntryType(input.readString());
              break;
            }
            case 26: {
              com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.Builder subBuilder = com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addApplacationHeader(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string version = 1;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public java.lang.String getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = getDefaultInstance().getVersion();
        return this;
      }
      
      // required string default_entry_type = 2;
      public boolean hasDefaultEntryType() {
        return result.hasDefaultEntryType();
      }
      public java.lang.String getDefaultEntryType() {
        return result.getDefaultEntryType();
      }
      public Builder setDefaultEntryType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDefaultEntryType = true;
        result.defaultEntryType_ = value;
        return this;
      }
      public Builder clearDefaultEntryType() {
        result.hasDefaultEntryType = false;
        result.defaultEntryType_ = getDefaultInstance().getDefaultEntryType();
        return this;
      }
      
      // repeated .protoStream.ApplacationHeader applacation_header = 3;
      public java.util.List<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader> getApplacationHeaderList() {
        return java.util.Collections.unmodifiableList(result.applacationHeader_);
      }
      public int getApplacationHeaderCount() {
        return result.getApplacationHeaderCount();
      }
      public com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader getApplacationHeader(int index) {
        return result.getApplacationHeader(index);
      }
      public Builder setApplacationHeader(int index, com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.applacationHeader_.set(index, value);
        return this;
      }
      public Builder setApplacationHeader(int index, com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.Builder builderForValue) {
        result.applacationHeader_.set(index, builderForValue.build());
        return this;
      }
      public Builder addApplacationHeader(com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.applacationHeader_.isEmpty()) {
          result.applacationHeader_ = new java.util.ArrayList<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader>();
        }
        result.applacationHeader_.add(value);
        return this;
      }
      public Builder addApplacationHeader(com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.Builder builderForValue) {
        if (result.applacationHeader_.isEmpty()) {
          result.applacationHeader_ = new java.util.ArrayList<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader>();
        }
        result.applacationHeader_.add(builderForValue.build());
        return this;
      }
      public Builder addAllApplacationHeader(
          java.lang.Iterable<? extends com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader> values) {
        if (result.applacationHeader_.isEmpty()) {
          result.applacationHeader_ = new java.util.ArrayList<com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader>();
        }
        super.addAll(values, result.applacationHeader_);
        return this;
      }
      public Builder clearApplacationHeader() {
        result.applacationHeader_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protoStream.ProtoStreamHeader)
    }
    
    static {
      defaultInstance = new ProtoStreamHeader(true);
      com.spinn3r.api.protobuf.ProtoStream.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protoStream.ProtoStreamHeader)
  }
  
  public static final class ProtoStreamDelimiter extends
      com.google.protobuf.GeneratedMessage {
    // Use ProtoStreamDelimiter.newBuilder() to construct.
    private ProtoStreamDelimiter() {
      initFields();
    }
    private ProtoStreamDelimiter(boolean noInit) {}
    
    private static final ProtoStreamDelimiter defaultInstance;
    public static ProtoStreamDelimiter getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoStreamDelimiter getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ProtoStreamDelimiter_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protobuf.ProtoStream.internal_static_protoStream_ProtoStreamDelimiter_fieldAccessorTable;
    }
    
    public enum DelimiterType
        implements com.google.protobuf.ProtocolMessageEnum {
      ENTRY(0, 1),
      END(1, 2),
      INDEX(2, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static DelimiterType valueOf(int value) {
        switch (value) {
          case 1: return ENTRY;
          case 2: return END;
          case 3: return INDEX;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DelimiterType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DelimiterType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DelimiterType>() {
              public DelimiterType findValueByNumber(int number) {
                return DelimiterType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final DelimiterType[] VALUES = {
        ENTRY, END, INDEX, 
      };
      public static DelimiterType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private DelimiterType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.spinn3r.api.protobuf.ProtoStream.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:protoStream.ProtoStreamDelimiter.DelimiterType)
    }
    
    // optional .protoStream.ProtoStreamDelimiter.DelimiterType delimiter_type = 1 [default = END];
    public static final int DELIMITER_TYPE_FIELD_NUMBER = 1;
    private boolean hasDelimiterType;
    private com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType delimiterType_;
    public boolean hasDelimiterType() { return hasDelimiterType; }
    public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType getDelimiterType() { return delimiterType_; }
    
    private void initFields() {
      delimiterType_ = com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType.END;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDelimiterType()) {
        output.writeEnum(1, getDelimiterType().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDelimiterType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getDelimiterType().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter result;
      
      // Construct using com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter();
        return builder;
      }
      
      protected com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.getDescriptor();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter getDefaultInstanceForType() {
        return com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter) {
          return mergeFrom((com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter other) {
        if (other == com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.getDefaultInstance()) return this;
        if (other.hasDelimiterType()) {
          setDelimiterType(other.getDelimiterType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType value = com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setDelimiterType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional .protoStream.ProtoStreamDelimiter.DelimiterType delimiter_type = 1 [default = END];
      public boolean hasDelimiterType() {
        return result.hasDelimiterType();
      }
      public com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType getDelimiterType() {
        return result.getDelimiterType();
      }
      public Builder setDelimiterType(com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDelimiterType = true;
        result.delimiterType_ = value;
        return this;
      }
      public Builder clearDelimiterType() {
        result.hasDelimiterType = false;
        result.delimiterType_ = com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.DelimiterType.END;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protoStream.ProtoStreamDelimiter)
    }
    
    static {
      defaultInstance = new ProtoStreamDelimiter(true);
      com.spinn3r.api.protobuf.ProtoStream.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protoStream.ProtoStreamDelimiter)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoStream_ApplacationHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoStream_ApplacationHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoStream_ProtoStreamHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoStream_ProtoStreamHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoStream_ProtoStreamDelimiter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoStream_ProtoStreamDelimiter_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021protoStream.proto\022\013protoStream\"0\n\021Appl" +
      "acationHeader\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \001" +
      "(\t\"|\n\021ProtoStreamHeader\022\017\n\007version\030\001 \002(\t" +
      "\022\032\n\022default_entry_type\030\002 \002(\t\022:\n\022applacat" +
      "ion_header\030\003 \003(\0132\036.protoStream.Applacati" +
      "onHeader\"\224\001\n\024ProtoStreamDelimiter\022L\n\016del" +
      "imiter_type\030\001 \001(\0162/.protoStream.ProtoStr" +
      "eamDelimiter.DelimiterType:\003END\".\n\rDelim" +
      "iterType\022\t\n\005ENTRY\020\001\022\007\n\003END\020\002\022\t\n\005INDEX\020\003B" +
      "\'\n\030com.spinn3r.api.protobufB\013ProtoStream"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoStream_ApplacationHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoStream_ApplacationHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoStream_ApplacationHeader_descriptor,
              new java.lang.String[] { "Name", "Value", },
              com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.class,
              com.spinn3r.api.protobuf.ProtoStream.ApplacationHeader.Builder.class);
          internal_static_protoStream_ProtoStreamHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoStream_ProtoStreamHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoStream_ProtoStreamHeader_descriptor,
              new java.lang.String[] { "Version", "DefaultEntryType", "ApplacationHeader", },
              com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.class,
              com.spinn3r.api.protobuf.ProtoStream.ProtoStreamHeader.Builder.class);
          internal_static_protoStream_ProtoStreamDelimiter_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protoStream_ProtoStreamDelimiter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoStream_ProtoStreamDelimiter_descriptor,
              new java.lang.String[] { "DelimiterType", },
              com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.class,
              com.spinn3r.api.protobuf.ProtoStream.ProtoStreamDelimiter.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
