// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.spinn3r.api.protocolbuffers;

public final class Spinn3rApi {
  private Spinn3rApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Content extends
      com.google.protobuf.GeneratedMessage {
    // Use Content.newBuilder() to construct.
    private Content() {}
    
    private static final Content defaultInstance = new Content();
    public static Content getDefaultInstance() {
      return defaultInstance;
    }
    
    public Content getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Content_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Content_fieldAccessorTable;
    }
    
    // required string mime_type = 1;
    private boolean hasMimeType;
    private java.lang.String mimeType_ = "";
    public boolean hasMimeType() { return hasMimeType; }
    public java.lang.String getMimeType() { return mimeType_; }
    
    // optional bytes content = 2;
    private boolean hasContent;
    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasContent() { return hasContent; }
    public com.google.protobuf.ByteString getContent() { return content_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Content result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Content();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Content internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Content();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Content buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content buildPartial() {
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Content returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string mime_type = 1;
      public boolean hasMimeType() {
        return result.hasMimeType();
      }
      public java.lang.String getMimeType() {
        return result.getMimeType();
      }
      public Builder setMimeType(java.lang.String value) {
        result.hasMimeType = true;
        result.mimeType_ = value;
        return this;
      }
      public Builder clearMimeType() {
        result.hasMimeType = false;
        result.mimeType_ = "";
        return this;
      }
      
      // optional bytes content = 2;
      public boolean hasContent() {
        return result.hasContent();
      }
      public com.google.protobuf.ByteString getContent() {
        return result.getContent();
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder clearContent() {
        result.hasContent = false;
        result.content_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {}
    
    private static final Response defaultInstance = new Response();
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Response_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Response_fieldAccessorTable;
    }
    
    // optional string source = 1;
    private boolean hasSource;
    private java.lang.String source_ = "";
    public boolean hasSource() { return hasSource; }
    public java.lang.String getSource() { return source_; }
    
    // optional string previous_request_url = 2;
    private boolean hasPreviousRequestUrl;
    private java.lang.String previousRequestUrl_ = "";
    public boolean hasPreviousRequestUrl() { return hasPreviousRequestUrl; }
    public java.lang.String getPreviousRequestUrl() { return previousRequestUrl_; }
    
    // optional string next_request_url = 3;
    private boolean hasNextRequestUrl;
    private java.lang.String nextRequestUrl_ = "";
    public boolean hasNextRequestUrl() { return hasNextRequestUrl; }
    public java.lang.String getNextRequestUrl() { return nextRequestUrl_; }
    
    // repeated .spinn3rApi.Entry entries = 4;
    private java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry> entries_ =
      java.util.Collections.emptyList();
    public java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry> getEntriesList() {
      return entries_;
    }
    public int getEntriesCount() { return entries_.size(); }
    public com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry getEntries(int index) {
      return entries_.get(index);
    }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Response prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Response.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Response result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Response();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Response internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Response();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Response.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Response getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Response.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Response build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Response buildPartial() {
        if (result.entries_ != java.util.Collections.EMPTY_LIST) {
          result.entries_ =
            java.util.Collections.unmodifiableList(result.entries_);
        }
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string source = 1;
      public boolean hasSource() {
        return result.hasSource();
      }
      public java.lang.String getSource() {
        return result.getSource();
      }
      public Builder setSource(java.lang.String value) {
        result.hasSource = true;
        result.source_ = value;
        return this;
      }
      public Builder clearSource() {
        result.hasSource = false;
        result.source_ = "";
        return this;
      }
      
      // optional string previous_request_url = 2;
      public boolean hasPreviousRequestUrl() {
        return result.hasPreviousRequestUrl();
      }
      public java.lang.String getPreviousRequestUrl() {
        return result.getPreviousRequestUrl();
      }
      public Builder setPreviousRequestUrl(java.lang.String value) {
        result.hasPreviousRequestUrl = true;
        result.previousRequestUrl_ = value;
        return this;
      }
      public Builder clearPreviousRequestUrl() {
        result.hasPreviousRequestUrl = false;
        result.previousRequestUrl_ = "";
        return this;
      }
      
      // optional string next_request_url = 3;
      public boolean hasNextRequestUrl() {
        return result.hasNextRequestUrl();
      }
      public java.lang.String getNextRequestUrl() {
        return result.getNextRequestUrl();
      }
      public Builder setNextRequestUrl(java.lang.String value) {
        result.hasNextRequestUrl = true;
        result.nextRequestUrl_ = value;
        return this;
      }
      public Builder clearNextRequestUrl() {
        result.hasNextRequestUrl = false;
        result.nextRequestUrl_ = "";
        return this;
      }
      
      // repeated .spinn3rApi.Entry entries = 4;
      public java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry> getEntriesList() {
        return java.util.Collections.unmodifiableList(result.entries_);
      }
      public int getEntriesCount() {
        return result.getEntriesCount();
      }
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry getEntries(int index) {
        return result.getEntries(index);
      }
      public Builder setEntries(int index, com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry value) {
        result.entries_.set(index, value);
        return this;
      }
      public Builder setEntries(int index, com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.Builder builderForValue) {
        result.entries_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEntries(com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry value) {
        if (result.entries_.isEmpty()) {
          result.entries_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry>();
        }
        result.entries_.add(value);
        return this;
      }
      public Builder addEntries(com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.Builder builderForValue) {
        if (result.entries_.isEmpty()) {
          result.entries_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry>();
        }
        result.entries_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEntries(
          java.lang.Iterable<? extends com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry> values) {
        if (result.entries_.isEmpty()) {
          result.entries_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry>();
        }
        super.addAll(values, result.entries_);
        return this;
      }
      public Builder clearEntries() {
        result.entries_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class Author extends
      com.google.protobuf.GeneratedMessage {
    // Use Author.newBuilder() to construct.
    private Author() {}
    
    private static final Author defaultInstance = new Author();
    public static Author getDefaultInstance() {
      return defaultInstance;
    }
    
    public Author getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Author_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Author_fieldAccessorTable;
    }
    
    // optional string name = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string email = 2;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // optional string link = 3;
    private boolean hasLink;
    private java.lang.String link_ = "";
    public boolean hasLink() { return hasLink; }
    public java.lang.String getLink() { return link_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Author parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Author prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Author result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Author();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Author internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Author();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Author getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Author build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Author buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Author buildPartial() {
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Author returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional string email = 2;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = "";
        return this;
      }
      
      // optional string link = 3;
      public boolean hasLink() {
        return result.hasLink();
      }
      public java.lang.String getLink() {
        return result.getLink();
      }
      public Builder setLink(java.lang.String value) {
        result.hasLink = true;
        result.link_ = value;
        return this;
      }
      public Builder clearLink() {
        result.hasLink = false;
        result.link_ = "";
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class Source extends
      com.google.protobuf.GeneratedMessage {
    // Use Source.newBuilder() to construct.
    private Source() {}
    
    private static final Source defaultInstance = new Source();
    public static Source getDefaultInstance() {
      return defaultInstance;
    }
    
    public Source getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Source_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Source_fieldAccessorTable;
    }
    
    // optional string resource = 1;
    private boolean hasResource;
    private java.lang.String resource_ = "";
    public boolean hasResource() { return hasResource; }
    public java.lang.String getResource() { return resource_; }
    
    // optional string title = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional string description = 3;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional sint32 tier = 4;
    private boolean hasTier;
    private int tier_ = 0;
    public boolean hasTier() { return hasTier; }
    public int getTier() { return tier_; }
    
    // optional int32 indegree = 5;
    private boolean hasIndegree;
    private int indegree_ = 0;
    public boolean hasIndegree() { return hasIndegree; }
    public int getIndegree() { return indegree_; }
    
    // optional int32 iranking = 6;
    private boolean hasIranking;
    private int iranking_ = 0;
    public boolean hasIranking() { return hasIranking; }
    public int getIranking() { return iranking_; }
    
    // optional string publisher_type = 7;
    private boolean hasPublisherType;
    private java.lang.String publisherType_ = "";
    public boolean hasPublisherType() { return hasPublisherType; }
    public java.lang.String getPublisherType() { return publisherType_; }
    
    // optional string hashcode = 8;
    private boolean hasHashcode;
    private java.lang.String hashcode_ = "";
    public boolean hasHashcode() { return hasHashcode; }
    public java.lang.String getHashcode() { return hashcode_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Source parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Source prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Source.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Source result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Source();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Source internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Source();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Source.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Source getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Source.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Source build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Source buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Source buildPartial() {
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Source returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string resource = 1;
      public boolean hasResource() {
        return result.hasResource();
      }
      public java.lang.String getResource() {
        return result.getResource();
      }
      public Builder setResource(java.lang.String value) {
        result.hasResource = true;
        result.resource_ = value;
        return this;
      }
      public Builder clearResource() {
        result.hasResource = false;
        result.resource_ = "";
        return this;
      }
      
      // optional string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional string description = 3;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = "";
        return this;
      }
      
      // optional sint32 tier = 4;
      public boolean hasTier() {
        return result.hasTier();
      }
      public int getTier() {
        return result.getTier();
      }
      public Builder setTier(int value) {
        result.hasTier = true;
        result.tier_ = value;
        return this;
      }
      public Builder clearTier() {
        result.hasTier = false;
        result.tier_ = 0;
        return this;
      }
      
      // optional int32 indegree = 5;
      public boolean hasIndegree() {
        return result.hasIndegree();
      }
      public int getIndegree() {
        return result.getIndegree();
      }
      public Builder setIndegree(int value) {
        result.hasIndegree = true;
        result.indegree_ = value;
        return this;
      }
      public Builder clearIndegree() {
        result.hasIndegree = false;
        result.indegree_ = 0;
        return this;
      }
      
      // optional int32 iranking = 6;
      public boolean hasIranking() {
        return result.hasIranking();
      }
      public int getIranking() {
        return result.getIranking();
      }
      public Builder setIranking(int value) {
        result.hasIranking = true;
        result.iranking_ = value;
        return this;
      }
      public Builder clearIranking() {
        result.hasIranking = false;
        result.iranking_ = 0;
        return this;
      }
      
      // optional string publisher_type = 7;
      public boolean hasPublisherType() {
        return result.hasPublisherType();
      }
      public java.lang.String getPublisherType() {
        return result.getPublisherType();
      }
      public Builder setPublisherType(java.lang.String value) {
        result.hasPublisherType = true;
        result.publisherType_ = value;
        return this;
      }
      public Builder clearPublisherType() {
        result.hasPublisherType = false;
        result.publisherType_ = "";
        return this;
      }
      
      // optional string hashcode = 8;
      public boolean hasHashcode() {
        return result.hasHashcode();
      }
      public java.lang.String getHashcode() {
        return result.getHashcode();
      }
      public Builder setHashcode(java.lang.String value) {
        result.hasHashcode = true;
        result.hashcode_ = value;
        return this;
      }
      public Builder clearHashcode() {
        result.hasHashcode = false;
        result.hashcode_ = "";
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class FeedEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use FeedEntry.newBuilder() to construct.
    private FeedEntry() {}
    
    private static final FeedEntry defaultInstance = new FeedEntry();
    public static FeedEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public FeedEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_FeedEntry_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_FeedEntry_fieldAccessorTable;
    }
    
    // repeated string category = 1;
    private java.util.List<java.lang.String> category_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getCategoryList() {
      return category_;
    }
    public int getCategoryCount() { return category_.size(); }
    public java.lang.String getCategory(int index) {
      return category_.get(index);
    }
    
    // repeated .spinn3rApi.Author author = 2;
    private java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author> author_ =
      java.util.Collections.emptyList();
    public java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author> getAuthorList() {
      return author_;
    }
    public int getAuthorCount() { return author_.size(); }
    public com.spinn3r.api.protocolbuffers.Spinn3rApi.Author getAuthor(int index) {
      return author_.get(index);
    }
    
    // optional string hashcode = 3;
    private boolean hasHashcode;
    private java.lang.String hashcode_ = "";
    public boolean hasHashcode() { return hasHashcode; }
    public java.lang.String getHashcode() { return hashcode_; }
    
    // optional int64 identifier = 4;
    private boolean hasIdentifier;
    private long identifier_ = 0L;
    public boolean hasIdentifier() { return hasIdentifier; }
    public long getIdentifier() { return identifier_; }
    
    // optional string title = 5;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional string last_published = 6;
    private boolean hasLastPublished;
    private java.lang.String lastPublished_ = "";
    public boolean hasLastPublished() { return hasLastPublished; }
    public java.lang.String getLastPublished() { return lastPublished_; }
    
    // optional string date_found = 7;
    private boolean hasDateFound;
    private java.lang.String dateFound_ = "";
    public boolean hasDateFound() { return hasDateFound; }
    public java.lang.String getDateFound() { return dateFound_; }
    
    // optional .spinn3rApi.Content body = 8;
    private boolean hasBody;
    private com.spinn3r.api.protocolbuffers.Spinn3rApi.Content body_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
    public boolean hasBody() { return hasBody; }
    public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getBody() { return body_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry buildPartial() {
        if (result.category_ != java.util.Collections.EMPTY_LIST) {
          result.category_ =
            java.util.Collections.unmodifiableList(result.category_);
        }
        if (result.author_ != java.util.Collections.EMPTY_LIST) {
          result.author_ =
            java.util.Collections.unmodifiableList(result.author_);
        }
        com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated string category = 1;
      public java.util.List<java.lang.String> getCategoryList() {
        return java.util.Collections.unmodifiableList(result.category_);
      }
      public int getCategoryCount() {
        return result.getCategoryCount();
      }
      public java.lang.String getCategory(int index) {
        return result.getCategory(index);
      }
      public Builder setCategory(int index, java.lang.String value) {
        result.category_.set(index, value);
        return this;
      }
      public Builder addCategory(java.lang.String value) {
        if (result.category_.isEmpty()) {
          result.category_ = new java.util.ArrayList<java.lang.String>();
        }
        result.category_.add(value);
        return this;
      }
      public Builder addAllCategory(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.category_.isEmpty()) {
          result.category_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.category_);
        return this;
      }
      public Builder clearCategory() {
        result.category_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .spinn3rApi.Author author = 2;
      public java.util.List<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author> getAuthorList() {
        return java.util.Collections.unmodifiableList(result.author_);
      }
      public int getAuthorCount() {
        return result.getAuthorCount();
      }
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Author getAuthor(int index) {
        return result.getAuthor(index);
      }
      public Builder setAuthor(int index, com.spinn3r.api.protocolbuffers.Spinn3rApi.Author value) {
        result.author_.set(index, value);
        return this;
      }
      public Builder setAuthor(int index, com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.Builder builderForValue) {
        result.author_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAuthor(com.spinn3r.api.protocolbuffers.Spinn3rApi.Author value) {
        if (result.author_.isEmpty()) {
          result.author_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author>();
        }
        result.author_.add(value);
        return this;
      }
      public Builder addAuthor(com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.Builder builderForValue) {
        if (result.author_.isEmpty()) {
          result.author_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author>();
        }
        result.author_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAuthor(
          java.lang.Iterable<? extends com.spinn3r.api.protocolbuffers.Spinn3rApi.Author> values) {
        if (result.author_.isEmpty()) {
          result.author_ = new java.util.ArrayList<com.spinn3r.api.protocolbuffers.Spinn3rApi.Author>();
        }
        super.addAll(values, result.author_);
        return this;
      }
      public Builder clearAuthor() {
        result.author_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string hashcode = 3;
      public boolean hasHashcode() {
        return result.hasHashcode();
      }
      public java.lang.String getHashcode() {
        return result.getHashcode();
      }
      public Builder setHashcode(java.lang.String value) {
        result.hasHashcode = true;
        result.hashcode_ = value;
        return this;
      }
      public Builder clearHashcode() {
        result.hasHashcode = false;
        result.hashcode_ = "";
        return this;
      }
      
      // optional int64 identifier = 4;
      public boolean hasIdentifier() {
        return result.hasIdentifier();
      }
      public long getIdentifier() {
        return result.getIdentifier();
      }
      public Builder setIdentifier(long value) {
        result.hasIdentifier = true;
        result.identifier_ = value;
        return this;
      }
      public Builder clearIdentifier() {
        result.hasIdentifier = false;
        result.identifier_ = 0L;
        return this;
      }
      
      // optional string title = 5;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional string last_published = 6;
      public boolean hasLastPublished() {
        return result.hasLastPublished();
      }
      public java.lang.String getLastPublished() {
        return result.getLastPublished();
      }
      public Builder setLastPublished(java.lang.String value) {
        result.hasLastPublished = true;
        result.lastPublished_ = value;
        return this;
      }
      public Builder clearLastPublished() {
        result.hasLastPublished = false;
        result.lastPublished_ = "";
        return this;
      }
      
      // optional string date_found = 7;
      public boolean hasDateFound() {
        return result.hasDateFound();
      }
      public java.lang.String getDateFound() {
        return result.getDateFound();
      }
      public Builder setDateFound(java.lang.String value) {
        result.hasDateFound = true;
        result.dateFound_ = value;
        return this;
      }
      public Builder clearDateFound() {
        result.hasDateFound = false;
        result.dateFound_ = "";
        return this;
      }
      
      // optional .spinn3rApi.Content body = 8;
      public boolean hasBody() {
        return result.hasBody();
      }
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getBody() {
        return result.getBody();
      }
      public Builder setBody(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        result.hasBody = true;
        result.body_ = value;
        return this;
      }
      public Builder setBody(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.Builder builderForValue) {
        result.hasBody = true;
        result.body_ = builderForValue.build();
        return this;
      }
      public Builder mergeBody(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        if (result.hasBody() &&
            result.body_ != com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance()) {
          result.body_ =
            com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.newBuilder(result.body_).mergeFrom(value).buildPartial();
        } else {
          result.body_ = value;
        }
        result.hasBody = true;
        return this;
      }
      public Builder clearBody() {
        result.hasBody = false;
        result.body_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class Feed extends
      com.google.protobuf.GeneratedMessage {
    // Use Feed.newBuilder() to construct.
    private Feed() {}
    
    private static final Feed defaultInstance = new Feed();
    public static Feed getDefaultInstance() {
      return defaultInstance;
    }
    
    public Feed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Feed_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Feed_fieldAccessorTable;
    }
    
    // optional string link = 1;
    private boolean hasLink;
    private java.lang.String link_ = "";
    public boolean hasLink() { return hasLink; }
    public java.lang.String getLink() { return link_; }
    
    // optional string hashcode = 2;
    private boolean hasHashcode;
    private java.lang.String hashcode_ = "";
    public boolean hasHashcode() { return hasHashcode; }
    public java.lang.String getHashcode() { return hashcode_; }
    
    // optional string url = 3;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed buildPartial() {
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string link = 1;
      public boolean hasLink() {
        return result.hasLink();
      }
      public java.lang.String getLink() {
        return result.getLink();
      }
      public Builder setLink(java.lang.String value) {
        result.hasLink = true;
        result.link_ = value;
        return this;
      }
      public Builder clearLink() {
        result.hasLink = false;
        result.link_ = "";
        return this;
      }
      
      // optional string hashcode = 2;
      public boolean hasHashcode() {
        return result.hasHashcode();
      }
      public java.lang.String getHashcode() {
        return result.getHashcode();
      }
      public Builder setHashcode(java.lang.String value) {
        result.hasHashcode = true;
        result.hashcode_ = value;
        return this;
      }
      public Builder clearHashcode() {
        result.hasHashcode = false;
        result.hashcode_ = "";
        return this;
      }
      
      // optional string url = 3;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage {
    // Use Entry.newBuilder() to construct.
    private Entry() {}
    
    private static final Entry defaultInstance = new Entry();
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }
    
    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Entry_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.spinn3r.api.protocolbuffers.Spinn3rApi.internal_static_spinn3rApi_Entry_fieldAccessorTable;
    }
    
    // optional string title = 1;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional string link = 2;
    private boolean hasLink;
    private java.lang.String link_ = "";
    public boolean hasLink() { return hasLink; }
    public java.lang.String getLink() { return link_; }
    
    // optional string lang = 3;
    private boolean hasLang;
    private java.lang.String lang_ = "";
    public boolean hasLang() { return hasLang; }
    public java.lang.String getLang() { return lang_; }
    
    // optional .spinn3rApi.Content content = 4;
    private boolean hasContent;
    private com.spinn3r.api.protocolbuffers.Spinn3rApi.Content content_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
    public boolean hasContent() { return hasContent; }
    public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getContent() { return content_; }
    
    // optional .spinn3rApi.Content content_extract = 5;
    private boolean hasContentExtract;
    private com.spinn3r.api.protocolbuffers.Spinn3rApi.Content contentExtract_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
    public boolean hasContentExtract() { return hasContentExtract; }
    public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getContentExtract() { return contentExtract_; }
    
    // optional float spam_probability = 6;
    private boolean hasSpamProbability;
    private float spamProbability_ = 0F;
    public boolean hasSpamProbability() { return hasSpamProbability; }
    public float getSpamProbability() { return spamProbability_; }
    
    // optional string date_found = 7;
    private boolean hasDateFound;
    private java.lang.String dateFound_ = "";
    public boolean hasDateFound() { return hasDateFound; }
    public java.lang.String getDateFound() { return dateFound_; }
    
    // optional int64 identifier = 8;
    private boolean hasIdentifier;
    private long identifier_ = 0L;
    public boolean hasIdentifier() { return hasIdentifier; }
    public long getIdentifier() { return identifier_; }
    
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.newBuilder()
      private Builder() {}
      
      com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry();
      
      @Override
      protected com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.getDescriptor();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry getDefaultInstanceForType() {
        return com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.getDefaultInstance();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry buildPartial() {
        com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string title = 1;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional string link = 2;
      public boolean hasLink() {
        return result.hasLink();
      }
      public java.lang.String getLink() {
        return result.getLink();
      }
      public Builder setLink(java.lang.String value) {
        result.hasLink = true;
        result.link_ = value;
        return this;
      }
      public Builder clearLink() {
        result.hasLink = false;
        result.link_ = "";
        return this;
      }
      
      // optional string lang = 3;
      public boolean hasLang() {
        return result.hasLang();
      }
      public java.lang.String getLang() {
        return result.getLang();
      }
      public Builder setLang(java.lang.String value) {
        result.hasLang = true;
        result.lang_ = value;
        return this;
      }
      public Builder clearLang() {
        result.hasLang = false;
        result.lang_ = "";
        return this;
      }
      
      // optional .spinn3rApi.Content content = 4;
      public boolean hasContent() {
        return result.hasContent();
      }
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getContent() {
        return result.getContent();
      }
      public Builder setContent(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder setContent(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.Builder builderForValue) {
        result.hasContent = true;
        result.content_ = builderForValue.build();
        return this;
      }
      public Builder mergeContent(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        if (result.hasContent() &&
            result.content_ != com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance()) {
          result.content_ =
            com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.newBuilder(result.content_).mergeFrom(value).buildPartial();
        } else {
          result.content_ = value;
        }
        result.hasContent = true;
        return this;
      }
      public Builder clearContent() {
        result.hasContent = false;
        result.content_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
        return this;
      }
      
      // optional .spinn3rApi.Content content_extract = 5;
      public boolean hasContentExtract() {
        return result.hasContentExtract();
      }
      public com.spinn3r.api.protocolbuffers.Spinn3rApi.Content getContentExtract() {
        return result.getContentExtract();
      }
      public Builder setContentExtract(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        result.hasContentExtract = true;
        result.contentExtract_ = value;
        return this;
      }
      public Builder setContentExtract(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.Builder builderForValue) {
        result.hasContentExtract = true;
        result.contentExtract_ = builderForValue.build();
        return this;
      }
      public Builder mergeContentExtract(com.spinn3r.api.protocolbuffers.Spinn3rApi.Content value) {
        if (result.hasContentExtract() &&
            result.contentExtract_ != com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance()) {
          result.contentExtract_ =
            com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.newBuilder(result.contentExtract_).mergeFrom(value).buildPartial();
        } else {
          result.contentExtract_ = value;
        }
        result.hasContentExtract = true;
        return this;
      }
      public Builder clearContentExtract() {
        result.hasContentExtract = false;
        result.contentExtract_ = com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.getDefaultInstance();
        return this;
      }
      
      // optional float spam_probability = 6;
      public boolean hasSpamProbability() {
        return result.hasSpamProbability();
      }
      public float getSpamProbability() {
        return result.getSpamProbability();
      }
      public Builder setSpamProbability(float value) {
        result.hasSpamProbability = true;
        result.spamProbability_ = value;
        return this;
      }
      public Builder clearSpamProbability() {
        result.hasSpamProbability = false;
        result.spamProbability_ = 0F;
        return this;
      }
      
      // optional string date_found = 7;
      public boolean hasDateFound() {
        return result.hasDateFound();
      }
      public java.lang.String getDateFound() {
        return result.getDateFound();
      }
      public Builder setDateFound(java.lang.String value) {
        result.hasDateFound = true;
        result.dateFound_ = value;
        return this;
      }
      public Builder clearDateFound() {
        result.hasDateFound = false;
        result.dateFound_ = "";
        return this;
      }
      
      // optional int64 identifier = 8;
      public boolean hasIdentifier() {
        return result.hasIdentifier();
      }
      public long getIdentifier() {
        return result.getIdentifier();
      }
      public Builder setIdentifier(long value) {
        result.hasIdentifier = true;
        result.identifier_ = value;
        return this;
      }
      public Builder clearIdentifier() {
        result.hasIdentifier = false;
        result.identifier_ = 0L;
        return this;
      }
    }
    
    static {
      com.spinn3r.api.protocolbuffers.Spinn3rApi.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Content_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Content_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Author_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Author_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Source_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Source_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_FeedEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_FeedEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Feed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Feed_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_spinn3rApi_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spinn3rApi_Entry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\032src/proto/spinn3rApi.proto\022\nspinn3rApi" +
      "\"-\n\007Content\022\021\n\tmime_type\030\001 \002(\t\022\017\n\007conten" +
      "t\030\002 \001(\014\"v\n\010Response\022\016\n\006source\030\001 \001(\t\022\034\n\024p" +
      "revious_request_url\030\002 \001(\t\022\030\n\020next_reques" +
      "t_url\030\003 \001(\t\022\"\n\007entries\030\004 \003(\0132\021.spinn3rAp" +
      "i.Entry\"3\n\006Author\022\014\n\004name\030\001 \001(\t\022\r\n\005email" +
      "\030\002 \001(\t\022\014\n\004link\030\003 \001(\t\"\232\001\n\006Source\022\020\n\010resou" +
      "rce\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030" +
      "\003 \001(\t\022\014\n\004tier\030\004 \001(\021\022\020\n\010indegree\030\005 \001(\005\022\020\n" +
      "\010iranking\030\006 \001(\005\022\026\n\016publisher_type\030\007 \001(\t\022" +
      "\020\n\010hashcode\030\010 \001(\t\"\305\001\n\tFeedEntry\022\020\n\010categ" +
      "ory\030\001 \003(\t\022\"\n\006author\030\002 \003(\0132\022.spinn3rApi.A" +
      "uthor\022\020\n\010hashcode\030\003 \001(\t\022\022\n\nidentifier\030\004 " +
      "\001(\003\022\r\n\005title\030\005 \001(\t\022\026\n\016last_published\030\006 \001" +
      "(\t\022\022\n\ndate_found\030\007 \001(\t\022!\n\004body\030\010 \001(\0132\023.s" +
      "pinn3rApi.Content\"3\n\004Feed\022\014\n\004link\030\001 \001(\t\022" +
      "\020\n\010hashcode\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\"\310\001\n\005Entry" +
      "\022\r\n\005title\030\001 \001(\t\022\014\n\004link\030\002 \001(\t\022\014\n\004lang\030\003 " +
      "\001(\t\022$\n\007content\030\004 \001(\0132\023.spinn3rApi.Conten" +
      "t\022,\n\017content_extract\030\005 \001(\0132\023.spinn3rApi." +
      "Content\022\030\n\020spam_probability\030\006 \001(\002\022\022\n\ndat" +
      "e_found\030\007 \001(\t\022\022\n\nidentifier\030\010 \001(\003B-\n\037com" +
      ".spinn3r.api.protocolbuffersB\nSpinn3rApi";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_spinn3rApi_Content_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_spinn3rApi_Content_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Content_descriptor,
              new java.lang.String[] { "MimeType", "Content", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Content.Builder.class);
          internal_static_spinn3rApi_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_spinn3rApi_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Response_descriptor,
              new java.lang.String[] { "Source", "PreviousRequestUrl", "NextRequestUrl", "Entries", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Response.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Response.Builder.class);
          internal_static_spinn3rApi_Author_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_spinn3rApi_Author_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Author_descriptor,
              new java.lang.String[] { "Name", "Email", "Link", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Author.Builder.class);
          internal_static_spinn3rApi_Source_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_spinn3rApi_Source_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Source_descriptor,
              new java.lang.String[] { "Resource", "Title", "Description", "Tier", "Indegree", "Iranking", "PublisherType", "Hashcode", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Source.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Source.Builder.class);
          internal_static_spinn3rApi_FeedEntry_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_spinn3rApi_FeedEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_FeedEntry_descriptor,
              new java.lang.String[] { "Category", "Author", "Hashcode", "Identifier", "Title", "LastPublished", "DateFound", "Body", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.FeedEntry.Builder.class);
          internal_static_spinn3rApi_Feed_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_spinn3rApi_Feed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Feed_descriptor,
              new java.lang.String[] { "Link", "Hashcode", "Url", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Feed.Builder.class);
          internal_static_spinn3rApi_Entry_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_spinn3rApi_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_spinn3rApi_Entry_descriptor,
              new java.lang.String[] { "Title", "Link", "Lang", "Content", "ContentExtract", "SpamProbability", "DateFound", "Identifier", },
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.class,
              com.spinn3r.api.protocolbuffers.Spinn3rApi.Entry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
